apiVersion: v1
name: fluent-bit
description: Fast and lightweight log processor and forwarder or Linux, OSX and BSD family operating systems.
keywords:
  - logging
  - fluent-bit
  - fluentd
version: 0.44.0
appVersion: 2.2.2
icon: https://fluentbit.io/assets/img/logo1-default.png
home: https://fluentbit.io/
sources:
  - https://github.com/fluent/fluent-bit/
dependencies:
- name: fluent-bit
  version: 0.44.0
  repository: https://fluent.github.io/helm-charts
