fluent-bit:
  image:
    repository: "fluent/fluent-bit"
    tag: "latest"
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 100Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.deckhouse.io/group
            operator: NotIn
            values:
            - master
            - system
  podLabels:
    prometheus.deckhouse.io/custom-target: platformeco-fluent-bit
  podAnnotations:
    prometheus.deckhouse.io/port: "2020"
    prometheus.deckhouse.io/path: "/api/v1/metrics/prometheus"
  config:
    service: |
      [SERVICE]
          Daemon            Off
          Flush             5
          Log_Level         info
          Parsers_File      parsers.conf
          Parsers_File      custom_parsers.conf
          HTTP_Server       On
          HTTP_Listen       0.0.0.0
          HTTP_Port         2020
          Health_Check      On
          #Storage.path      /var/log/flb-storage/
          #Storage.metrics   On
    inputs: |
      [INPUT]
          Name                tail
          Tag                 kube.<namespace_name>.<pod_name>.<container_name>
          Tag_Regex           (?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-
          Path                /var/log/containers/*.log
          multiline.parser    docker, cri
          Exclude_Path        /var/log/containers/*fluent*.log,/var/log/containers/*d8-*.log,/var/log/containers/*_kube*.log,/var/log/containers/*telemetry-storage*.log,/var/log/containers/*mongos*.log,/var/log/containers/*aqua*.log,/var/log/containers/*starboard-operator*.log
          DB                  /var/log/flb_kube.db
          DB.locking          true
          DB.journal_mode     WAL
          Mem_Buf_Limit       512MB
          Refresh_Interval    3
          Buffer_Chunk_Size   256k
          Buffer_Max_Size     512k
          Storage.type        memory
    filters: |
      [FILTER]
          Name                  kubernetes
          Labels                Off
          Annotations           Off
          Match                 kube.*
          Kube_Tag_Prefix       kube.
          Regex_Parser          kubelogs
          Merge_Log             On
          Merge_Log_Trim        On
          Keep_Log              Off
          K8S-Logging.Parser    On
          K8S-Logging.Exclude   On
      [FILTER]
          Name        modify
          Match       kube.*
          Add         cluster_name yc-a-stage.platformeco.lmru.tech
      [FILTER]
          Name              grep
          Match             kube.*
          Exclude           log /INFO/
          Exclude           log /DEBUG/
    customParsers: |
      [PARSER]
          Name       kubelogs
          Format     regex
          Regex      (?<namespace_name>[^.]+)\.(?<pod_name>[^.]+)\.(?<container_name>[^.]+)
    outputs: |
      [OUTPUT]
          Name                      forward
          Match                     *
          Host                      fluentd-yc-a-stage.fluentd
          Port                      24224
          Retry_Limit               5
          Storage.total_limit_size  1024MB
          #Disabling tcp keepalive to keep log streams evenly distributed between fluentd instances
          Net.keepalive             off
