apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache.fullname" . }}-service
  labels:
    {{- include "apache.labels" . | nindent 4 }}
    app: apache
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: apache
  selector:
    {{- include "apache.selectorLabels" . | nindent 4 }}
    app: apache
