apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FlatSA/argocd-stand.git
    path: helm/argocd
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
